project_id = "meprfpbhzkijctzhvvvb"

[functions.delete-user-account]
verify_jwt = true

[functions.get-bestsellers]
verify_jwt = false

[functions.create-stripe-checkout]
verify_jwt = false

[functions.create-pagbank-checkout]
verify_jwt = false

[functions.pagbank-webhook]
verify_jwt = false

[functions.record-purchase]
verify_jwt = true
